# numpy.random package

#### In this Jupyter Notebook I intend to explain the use of the numpy.random package as part of an assignment for this module.


To initialy get my head around how the Jupyter Notebook works I followed Ian's example from the 'numpy.random docs' video on Moodle, and amended the code slightly to produce a different result. I applied the knowledge from an online source referred to by Ian - https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.random.html - and utilised the code 'rand' from this source whch is used to generate 'Random values in a given shape'. My results are shown below;

In [1]:
import numpy as np

In [7]:
np.random.rand(3,2,5)

array([[[0.74587623, 0.39820034, 0.05689761, 0.80348064, 0.61506251],
        [0.9288363 , 0.62312357, 0.42531836, 0.99979165, 0.23076853]],

       [[0.06729424, 0.21117458, 0.21698791, 0.71451403, 0.9876162 ],
        [0.95416815, 0.69503263, 0.12989598, 0.11422235, 0.64277163]],

       [[0.31760602, 0.78675748, 0.07064433, 0.8293661 , 0.65198261],
        [0.08536236, 0.27525669, 0.54481786, 0.11842335, 0.54897548]]])

#### The 4 tasks which I intend to carry out in this Jupyter notebook;
1.	Explain the overall purpose of the package.
2.	Explain the use of “Simple random data” and “Permutations” functions.
3.	Explain the use and purpose of at least five “Distribution” functions.
4.	Explain the use of seeds in generating pseudorandom numbers.


I tried to bear the above in mind while reviewing the videos.

### 1.	Explain the overall purpose of the numpy.random package.

numpy.random is a package for generating random data in Python.

I learned from Ian’s videos on Moodle that the numpy.random package is a sub package of the numpy package in Python. A lot of other packages depend on numpy, but not many interact with it directly, mainly interact with it through other packages.

Numpy.random is mainly to do with generating random numbers. Computers can’t generate random numbers – they can only generate pseudorandom numbers (for the time being!). There are a lot of different ways to generate different pseudorandom numbers.

Ian was observing the following webpage in the video; https://docs.scipy.org

##### What is NumPy?

*NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.*
(Reference: https://docs.scipy.org)

I learned that NumPy is exceptionally quick at dealing with numbers in long lists in Python – even lists contained within lists!

NumPy is a specialist package which deals with multidimensional arrays – it liked 2D/rectangular lists. It knows how to complete operations on the lists/arrays quickly. It has algorithms built into it. 

Typically we don’t create arrays in numpy, we use different packages such as numpy.random. 

Ian informed us in his video ‘Introduction to numpy’ that an example of one of the uses of numpy is a task which I complete regularly - resizing a photo, making it smaller, on my PC. The matrix operations behind this are usually linked with numpy, as it knows how to complete these operations quickly.

Setting up numpy.random repository video;
Note: Ian advised that we should shut down Jupyter before making any amendments in Git to prevent avoidable issues.

I learned from my research online that;
*An important part of any simulation is the ability to generate random numbers. For this purpose, NumPy provides various routines in the submodule random. It uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers.
First, we need to define a seed that makes the random numbers predictable. When the value is reset, the same numbers will appear every time. If we do not assign the seed, NumPy automatically selects a random seed value based on the system's random number generator device or on the clock*:

Copy
>>> np.random.seed(20)

(Reference: https://www.packtpub.com)


### 2.	Explain the use of “Simple random data” and “Permutations” functions.

I researched this online and took the below information from https://docs.scipy.org;

##### Permutations  
*Randomly permute a sequence, or return a permuted range.*

If x is a multi-dimensional array, it is only shuffled along its first index.

Parameters:
x : int or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.
 
Returns:
out : ndarray
Permuted sequence or array range.

On the video on Moodle named ‘numpy.random docs’ Ian stated that the Permutation section has 2 functions – one called ‘Shuffle’ and one called ‘Permutation’. 
They do similar things but Shuffle changes a numpy array which is already in place, whereas permutation doesn’t change what you pass into it. 

To Do: I should paste ‘permutaion’ & ‘shuffle’ into my Jupyter notebook in the same way in which Ian completed this for ‘rand’ and see what the outcome is.

##### Simple Random Data
*Used to generate random values in a given shape.*
Reference: https://www.gaussianwaves.com

An example of this is given below;


In [5]:
import numpy as np

In [6]:
np.random.rand(3,2,5)

array([[[0.10725744, 0.35395969, 0.75999121, 0.61280971, 0.91609332],
        [0.52276847, 0.70140487, 0.12671179, 0.14490461, 0.83766987]],

       [[0.12848813, 0.03754388, 0.43680506, 0.74440567, 0.34005425],
        [0.73957052, 0.5752561 , 0.64169654, 0.10871334, 0.90349609]],

       [[0.82022198, 0.36866667, 0.28520431, 0.1223283 , 0.0040476 ],
        [0.08486315, 0.44209301, 0.02927438, 0.20084771, 0.56169999]]])

### 3.	Explain the use and purpose of at least five “Distribution” functions.

Ian advised in the video on Moodle named ‘numpy.random docs’ that Distribution has different functions which relates to different probability distributions. Sometimes you may want to generate numbers which are not your typical random numbers.
I decided to explain the use & purpose of the following 5 ‘Distribution’ functions;

##### 1.	Uniform Distribution - 

Ian mentioned in Moodle video ‘Distributions’ that ‘Uniform’ implies that every number in the interval [0, 1) including 0 but not including 1 – has the same/equal chance of being generated.

I reviewed https://www.gaussianwaves.com and learned that Uniform Distribution is used for the following purpose;

*Continuous Uniform Random Variables are used to model a scenario where a continuous random variable can take values that are equally distributed (with equal probability) in an interval. Uniform distribution is the underlying distribution to model such random variables.*





In [9]:
np.random.uniform(-1,0,10)

array([-0.6261935 , -0.3605155 , -0.74376235, -0.54742423, -0.26957891,
       -0.16498661, -0.78084532, -0.00099696, -0.6556655 , -0.69665259])

##### 2.	Logistic Distribution – 
*Draw samples from a logistic distribution.
Samples are drawn from a logistic distribution with specified parameters, loc (location or mean, also median), and scale (>0).
The Logistic distribution is used in Extreme Value problems where it can act as a mixture of Gumbel distributions, in Epidemiology, and by the World Chess Federation (FIDE) where it is used in the Elo ranking system, assuming the performance of each player is a logistically distributed random variable.*
Reference: https://www.gaussianwaves.com

##### 3.	Geometric Distribution – 
*Draw samples from the geometric distribution.
Bernoulli trials are experiments with one of two outcomes: success or failure (an example of such an experiment is flipping a coin). The geometric distribution models the number of trials that must be run in order to achieve success.*
Reference: https://www.gaussianwaves.com

##### 4.	Multinomial Distribution – 
*The multinomial distribution is a multivariate generalisation of the binomial distribution. Take an experiment with one of p possible outcomes. An example of such an experiment is throwing a dice, where the outcome can be 1 through 6. Each sample drawn from the distribution represents n such experiments. Its values, X_i = [X_0, X_1, ..., X_p], represent the number of times the outcome was i.*
Reference: https://www.gaussianwaves.com

##### 5.	Normal Distribution - 
*Draw random samples from a normal (Gaussian) distribution.

*The probability density function of the normal distribution, first derived by De Moivre and 200 years later by both Gauss and Laplace independently [2], is often called the bell curve because of its characteristic shape (see the example below).

*The normal distributions occurs often in nature. For example, it describes the commonly occurring distribution of samples influenced by a large number of tiny, random disturbances, each with its own unique distribution [2].*
Reference: https://www.gaussianwaves.com


### 4.	Explain the use of seeds in generating pseudorandom numbers.

*A random seed (or seed state, or just seed) is a number (or vector) used to initialize a pseudorandom number generator. For a seed to be used in a pseudorandom number generator, it does not need to be random.*
Reference: https://en.wikipedia.org/wiki/Random_seed

Ian stated that computers can’t generate random numbers in the ‘Seeds’ video on Moodle. Computers need a mechanism to generate random numbers. If you’re generating a random number on a computer, you’re really generating a pseudorandom number – it looks random, but it is actually predictable if you have the key piece of information used by the computer, known as the ‘seed’. The numbers generated are based on that seed.

